Add option --skip-passed to skip passed reports
os-autoinst/openqa_review pull request #144
Opened 2021-06-02 17:28 UTC by perlpunk

Issue: https://progress.opensuse.org/issues/92957

2021-06-02 17:42 UTC, perlpunk commented
I don't know why the 3.6 test is failing. Some problem with flake8

2021-06-03 08:46 UTC, perlpunk commented
```
ERROR: InvocationError for command /home/travis/build/os-autoinst/openqa_review/.tox/flake8/bin/flake8 (exited with code 1)
```
Oh, apparently an "InvocationError" for flake8 doesn't mean that there was a problem with flake8. It simply means that the style check did not pass 😂

CI is passing now

2021-06-09 11:18 UTC, okurz requested changes
This looks very good already. I suggest you try to trim down the test data a bit to have less noisy content in the HTML (and json) files. Can you try to manually delete some sections, e.g. header and footer and see if tests still pass? Also likely a single passed and a single failed openQA job should be enough to prove the concept

2021-06-09 11:18 UTC, okurz commented on tests/test_openqa_review.py
> +    args.skip_passed = True
I suggest to trim down the report a bit by also adding `args.show_empty = False` here. Can you do that?

2021-06-09 11:18 UTC, okurz commented on tests/test_openqa_review.py
> +def test_skip_passed():
you are adding this test directly after the function `bugrefs_test_args_factory` but don't use it. Can you just move it above to line 412?

2021-06-09 13:40 UTC, perlpunk commented on tests/test_openqa_review.py
> +def test_skip_passed():
done

2021-06-09 13:40 UTC, perlpunk commented on tests/test_openqa_review.py
> +    args.skip_passed = True
done

2021-06-09 14:04 UTC, perlpunk commented
Here is a comparison of a call without and with `--skip-passed`:
```
openqa-review \
-J https://openqa.opensuse.org/group_overview/68,https://openqa.opensuse.org/group_overview/4\
 --include-softfails --no-empty-sections | markdown
```
![openqa-review-all](https://user-images.githubusercontent.com/688850/121369113-df355580-c93b-11eb-8abf-0bc8e6f839df.png)
```
openqa-review \
-J https://openqa.opensuse.org/group_overview/68,https://openqa.opensuse.org/group_overview/4\
 --include-softfails --no-empty-sections | markdown
```
![openqa-review-skip-passed](https://user-images.githubusercontent.com/688850/121369117-dfcdec00-c93b-11eb-9cf8-971b5f711e00.png)

I think that shows why I chose those two.

2021-06-09 14:05 UTC, perlpunk commented
> This looks very good already. I suggest you try to trim down the test data a bit to have less noisy content in the HTML (and json) files.

I deleted some HTML sections.

Not sure what to delete from JSON.
Should I sit down and try and delete things and re-add it again if the test fails? That might take a while.

2021-06-09 17:27 UTC, okurz approved these changes
Nice. All good. The JSON documents don't need further trimming, was merely "nice to have"

2021-06-09 17:27 UTC, merged