Surface last error from browser.get
os-autoinst/openqa_review pull request #147
Opened 2021-06-14 13:38 UTC by kalikiana

The retries don't preserve the exception or status code if we hit the for/else branch. Since we may not have a request I'm using a string.

See: https://progress.opensuse.org/issues/93943

2021-06-14 13:56 UTC, Martchus commented
This is already in conflict with master. Looks like you haven't based this on the current master branch.

2021-06-14 15:15 UTC, okurz reviewed
Looks like a good idea. Can you try to provide example output "before" and "after"?

2021-06-14 17:12 UTC, kalikiana commented
> Looks like a good idea. Can you try to provide example output "before" and "after"?

    openqa_review.browser.DownloadError: Request to https://test.openqa.suse.de/api/v1/parent_groups was not successful after 6 retries: HTTPSConnectionPool(host='test.openqa.suse.de', port=443): Max retries exceeded with url: /api/v1/parent_groups (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8b944f850>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Not sure there's a trivial way to make it more human-friendly, but this seems to produce a lot more useful errors here.

2021-06-16 10:54 UTC, perlpunk approved these changes

2021-06-16 10:55 UTC, perlpunk commented
There is a failing style check: https://travis-ci.com/github/os-autoinst/openqa_review/jobs/513686742#L208
(Very non-informative message though)

2021-06-16 13:33 UTC, okurz requested changes

2021-06-16 13:33 UTC, okurz commented on openqa_review/browser.py
> +        last_error = None
please instantiate the variable as close as possible where used, i.e. just before the `except`

2021-06-16 13:33 UTC, okurz commented on openqa_review/browser.py
> +                msg += ": {}".format(last_error)
Instead of checking for last_error and appending the ": " part here I suggest to initialize `last_error` with an empty string, add the ": " prefix where last_error is added with details and always concatenate. E.g. like

```python
last_error = ''
…
except requests.exceptions.ConnectionError as e:
    last_error = ": {}".format(str(e))
…
msg = "Request to {} was not successful after {} retries{}".format(url, i, last_error)
```

2021-06-21 09:36 UTC, kalikiana commented on openqa_review/browser.py
> +        last_error = None
It's used in the `for/else` branch so I assume it needs to be declared beforehand. Sicne I can't test all possible branches and there's no full test coverage I'd rather leave it there.

2021-06-21 12:47 UTC, okurz approved these changes

2021-06-21 12:47 UTC, merged