Increase the number of retries for browser.get
os-autoinst/openqa_review pull request #148
Opened 2021-06-21 14:36 UTC by kalikiana

See: [poo#93943](https://progress.opensuse.org/issues/93943)

2021-06-21 14:44 UTC, Martchus requested changes

2021-06-21 14:44 UTC, Martchus commented on openqa_review/browser.py
> +        for i in range(1, 21):
It looks like this loop doesn't have a delay between the retry attempts. However, I would refrain from hammering the server which is likely already busy enough in that situation even further. It would also make sense not to hardocde the number of retires here.

2021-06-21 14:53 UTC, okurz commented on openqa_review/browser.py
> +        for i in range(1, 21):
Better introduce an exponential time backoff

2021-06-22 09:02 UTC, kalikiana commented on openqa_review/browser.py
> +        for i in range(1, 21):
I decided to replace the loop entirely, see #149

2021-06-22 13:52 UTC, okurz commented
#149 looks promising

2021-06-22 13:52 UTC, closed without merging