Replace retry loop with Retry from urllib3
os-autoinst/openqa_review pull request #149
Opened 2021-06-22 09:01 UTC by kalikiana

See: https://progress.opensuse.org/issues/93943

2021-06-22 13:51 UTC, okurz requested changes

2021-06-22 13:51 UTC, okurz commented on openqa_review/browser.py
> +        http.mount("https://", HTTPAdapter(max_retries=retries))
what does the "https://" mean at this point? Why does it have to be specified? Does it prevent the use of http://?

2021-06-23 07:59 UTC, kalikiana commented on openqa_review/browser.py
> +        http.mount("https://", HTTPAdapter(max_retries=retries))
It means we have an adapter for the gven scheme. You could have different ones per scheme depending on requirements, see https://docs.python-requests.org/en/master/user/advanced/#transport-adapters
So yes. I need to add that as well here. Thank you for noticing!

2021-06-23 08:14 UTC, Martchus commented on openqa_review/browser.py
> +import urllib3
Looks like a new dependency. Do we need to add it somewhere?

2021-06-23 08:19 UTC, perlpunk commented on openqa_review/browser.py
> +import urllib3
probably here: https://github.com/os-autoinst/openqa_review/blob/master/setup.py#L33

2021-06-23 08:31 UTC, okurz commented on openqa_review/browser.py
> +        http.mount("https://", HTTPAdapter(max_retries=retries))
I suggest something like the following. Some lines below there is already `server_name = urlparse(url).netloc` which you can pull up here, for example:

```suggestion
        u = urlparse(url)
        http.mount(u.scheme, HTTPAdapter(max_retries=retries))
        …
        server_name = u.netloc
        
```

2021-06-23 09:11 UTC, okurz approved these changes

2021-06-23 09:11 UTC, merged