Fix relative import path for directly called testsuite
os-autoinst/openqa_review pull request #154
Opened 2021-06-24 13:36 UTC by asdil12

This will prevent confusion when the testsuite tries to
import the system wide installed `openqa_review` or fail
when called directly or with `py.test` insted of `tox`.

2021-06-24 14:46 UTC, perlpunk commented
In perl scripts we usually do (assuming modules are under `lib/`:
```
perl -Ilib bin/myscript
```
when executing a script from the source.

When working on PyYAML for example, I usually do `PYTHONPATH=lib3`

2021-06-24 15:05 UTC, kalikiana approved these changes

2021-06-24 20:25 UTC, okurz requested changes
What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has *only* the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.

I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [git-pr-last](http://github.com/okurz/scripts/tree/master/git-pr-last) to create a PR with proper description for these simple one-commit PRs:
```bash
$ cat $(which git-pr-last )
#!/bin/sh -e
target="${target:-"$USER"}"
git push $target && git show --no-patch --format=%B | hub pull-request -F -
```

See https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md#coding-style for more details.

Also, please try to find some reference showing that this is a recommended way in the python ecosystem.

2021-06-25 09:05 UTC, asdil12 commented
I updated the commit message.

That line is recommended [here](https://docs.python-guide.org/writing/structure/) and seems to come from the O'REILLY book "The Hitchhiker's Guide to Python".

2021-06-25 09:09 UTC, perlpunk approved these changes

2021-06-25 11:43 UTC, okurz approved these changes
> That line is recommended [here](https://docs.python-guide.org/writing/structure/) and seems to come from the O'REILLY book "The Hitchhiker's Guide to Python".

cool. More specifically https://docs.python-guide.org/writing/structure/#test-suite . Thank you. Something learned :)

2021-06-25 11:44 UTC, merged