Escape module names when fetching details json
os-autoinst/openqa_review pull request #165
Opened 2021-07-05 14:43 UTC by asdil12

This prevents issues with modules with a "#1" suffix

Ticket: https://progress.opensuse.org/issues/95033

2021-07-05 14:54 UTC, perlpunk reviewed
Can you add a test?

2021-07-06 08:14 UTC, okurz commented
> Can you add a test?

maybe just rename existing soft fail reference to have a "#1" included in the module name

2021-07-06 08:40 UTC, okurz reviewed
For a test please try

```diff

```--- a/tests/tags_labels/:tests:1316928
+++ b/tests/tags_labels/:tests:1316928
@@ -1,7 +1,7 @@
 <tr>
     <td class="component">
         <div>
-            <a href="/tests/1316928/modules/shutdown/steps/1/src">shutdown</a>
+            <a href="/tests/1316928/modules/shutdown%231/steps/1/src">shutdown#1</a>
         </div>
         <div class="flags">
         </div>
@@ -12,7 +12,7 @@
     <td class="links">
         <div class="links_a">
             <div class="fa fa-caret-up"></div>
-            <a class="no_hover" data-url="/tests/1316928/modules/shutdown/steps/9" href="#step/shutdown/9"
+            <a class="no_hover" data-url="/tests/1316928/modules/shutdown%231/steps/9" href="#step/shutdown/9"
                title="Soft Failed">
                 <span class="resborder resborder_hash(0x9c726c8)">Soft Failed</span>
             </a></div>

2021-07-06 10:55 UTC, okurz requested changes

2021-07-06 10:55 UTC, okurz commented on tests/test_openqa_review.py
> +    args.verbose = 5
please exclude that from your commit. If increasing the verbosity level makes sense then please in a separate commit + separate PR + not only for this subtest

2021-07-06 11:51 UTC, asdil12 commented on tests/test_openqa_review.py
> +    args.verbose = 5
when I add it globally for the factory, it breaks the testsuite.
I thought it makes sense here as it makes this very issue visible.

2021-07-06 12:03 UTC, asdil12 commented on tests/test_openqa_review.py
> +    args.verbose = 5
but I can leave it out for now and we can work in another PR on increasing the loglevel for the testsuite.

2021-07-06 12:18 UTC, Martchus approved these changes

2021-07-06 12:42 UTC, merged