Add option --todo-only
os-autoinst/openqa_review pull request #171
Opened 2021-07-15 10:11 UTC by perlpunk

In this view we only want to see TODO items in a compact list

Issue: https://progress.opensuse.org/issues/94762

2021-07-15 12:44 UTC, okurz requested changes
You are adding a lot of big test data. Please strip it down to the data that is needed to pass the tests

2021-07-15 12:44 UTC, okurz commented on openqa_review/openqa_review.py
> +        return True if (self.issues["new"]["todo"] or self.issues["existing"]["todo"]) else False
```suggestion
        """Tell if report has new or existing todo issues."""
        return self.issues["new"]["todo"] or self.issues["existing"]["todo"]
```

2021-07-15 12:44 UTC, okurz commented on openqa_review/openqa_review.py
> +            return self._todo_issues_str()
how about

```suggestion
            return self._todo_issues_str() if self.has_todo_issues() else ""
```

or at least

```suggestion
            if self.has_todo_issues():
                self._todo_issues_str()    
            return ""
```

2021-07-15 12:44 UTC, okurz commented on openqa_review/openqa_review.py
> +        help="List inly TODO items as one liners",
s/inly/only/

2021-07-15 12:44 UTC, okurz commented on openqa_review/openqa_review.py
> +                        report_str += "# %s\n\n%s\n---\n" % (k, generated_report)
hm, this becomes a bit convoluted. Let's see. How about:

```suggestion
                if not len(generated_report):
                    continue
                report_str += "* %s:\n%s" % (k, generated_report) if self.args.todo_only else "# %s\n\n%s\n---\n" % (k, generated_report)
```

2021-07-15 14:43 UTC, perlpunk commented on openqa_review/openqa_review.py
> +        return True if (self.issues["new"]["todo"] or self.issues["existing"]["todo"]) else False
done

2021-07-15 14:43 UTC, perlpunk commented on openqa_review/openqa_review.py
> +            return self._todo_issues_str()
done

2021-07-15 14:43 UTC, perlpunk commented on openqa_review/openqa_review.py
> +        help="List inly TODO items as one liners",
done

2021-07-15 14:50 UTC, perlpunk commented on openqa_review/openqa_review.py
> +                        report_str += "# %s\n\n%s\n---\n" % (k, generated_report)
done

2021-07-15 14:51 UTC, perlpunk commented
> You are adding a lot of big test data. Please strip it down to the data that is needed to pass the tests

Ok, I removed some parts in the JSON files

2021-07-15 16:32 UTC, perlpunk commented
I don't know how to fix the last issue.
https://app.travis-ci.com/github/os-autoinst/openqa_review/jobs/524734093
```
./openqa_review/openqa_review.py:1050:34: BLK100 Black would make changes.
```
It's nice to know that black would make changes, however it would be nicer to know which changes.

I can't find information on how to run this locally.

Calling `tox` results in a lot of errors.

`pip3 install -r requirements.txt` also results in an error
```
  Running setup.py develop for openqa-review
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/tina/openqa-devel/repos/openqa_review/setup.py'"'"'; __file__='"'"'/home/tina/openqa-devel/repos/openqa_review/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /home/tina/openqa-devel/repos/openqa_review/
    Complete output (30 lines):
    running develop
    /tmp/pip-build-env-uu0w1k6a/overlay/lib/python3.6/site-packages/setuptools/dist.py:502: UserWarning: The version specified ('1.25.0-15-g774e790') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % version
    WARNING: The user site-packages directory is disabled.
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/test-easy-install-4424.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/lib/python3.6/site-packages/
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    
    For information on other options, you may wish to consult the
    documentation at:
    
      https://setuptools.readthedocs.io/en/latest/easy_install.html
    
    Please make the appropriate changes for your system and try again.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/tina/openqa-devel/repos/openqa_review/setup.py'"'"'; __file__='"'"'/home/tina/openqa-devel/repos/openqa_review/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

2021-07-15 16:42 UTC, perlpunk commented
Calling `flake8 openqa_review/openqa_review.py` gives no output at all and a zero exit code.

2021-07-15 16:43 UTC, perlpunk commented
Aha, `.tox/black/bin/black openqa_review/openqa_review.py` reformatted the file for me

2021-07-15 20:11 UTC, okurz commented on openqa_review/openqa_review.py
> +        return True if (self.issues["new"]["todo"] or self.issues["existing"]["todo"]) else False
I also suggested to change this line. Just return the result of the evaluation directly, don't return True/False

2021-07-15 20:16 UTC, okurz requested changes
Hm, some JSON files seem to be really big still. Also please remove more from the html documents. As you now have a working test that should be trivial to do. Remove lines, run the test, continue

2021-07-15 20:16 UTC, okurz commented on tests/test_openqa_review.py
> +    compare_report(report, os.path.join(args.load_dir, "report-2-24-35.md"))
I suggest to rename the report `report-todo_only.md` or similar

2021-07-16 15:41 UTC, perlpunk commented on tests/test_openqa_review.py
> +    compare_report(report, os.path.join(args.load_dir, "report-2-24-35.md"))
done

2021-07-16 15:41 UTC, perlpunk commented on openqa_review/openqa_review.py
> +        return True if (self.issues["new"]["todo"] or self.issues["existing"]["todo"]) else False
done

2021-07-16 15:46 UTC, perlpunk commented
> Hm, some JSON files seem to be really big still. Also please remove more from the html documents.

I think I removed pretty much everything possible now

2021-07-16 16:00 UTC, perlpunk commented
https://app.travis-ci.com/github/os-autoinst/openqa_review/jobs/524978936#L223
```
File "/home/travis/build/os-autoinst/openqa_review/.tox/flake8/lib/python3.6/site-packages/flake8_black.py", line 11, in <module>
224    import toml
225ModuleNotFoundError: No module named 'toml'
```
What am I supposed to do here?

2021-07-18 07:39 UTC, okurz approved these changes

2021-07-18 07:40 UTC, okurz commented
I don't know about the toml problem. Maybe recent dependency problem of black?

2021-07-19 11:39 UTC, perlpunk commented
I force-pushed, and now it passed...

2021-07-19 12:10 UTC, merged