Retrieve comments from redmine tickets
os-autoinst/openqa_review pull request #190
Opened 2021-11-04 21:08 UTC by perlpunk

Issue: https://progress.opensuse.org/issues/101722

2021-11-08 17:44 UTC, Martchus reviewed
Looks generally good. It seems that the test adjustments are merely about side-effects, though. So maybe it is worth improving the tests.

2021-11-08 19:22 UTC, okurz requested changes

2021-11-08 19:22 UTC, okurz commented on openqa_review/openqa_review.py
> +    """ Initialize data for redmine issues. """
this comment line should go below the "def" line so that it's linked to the method. Compare to https://github.com/os-autoinst/openqa_review/pull/190/files#diff-be94a72b7e1901d8b710ae2351110a5b0cbb4ee91fa11f7eb7c495582c4bd27eR659

2021-11-08 19:22 UTC, okurz commented on openqa_review/openqa_review.py
> +    """ Initialize data for bugzilla issues. """
same here

2021-11-09 14:28 UTC, perlpunk commented on openqa_review/openqa_review.py
> +    """ Initialize data for redmine issues. """
done

2021-11-09 14:28 UTC, perlpunk commented on openqa_review/openqa_review.py
> +    """ Initialize data for bugzilla issues. """
done

2021-11-09 14:32 UTC, okurz commented on openqa_review/openqa_review.py
> +    """ Initialize data for redmine issues. """
you still need the blank lines, see https://app.travis-ci.com/github/os-autoinst/openqa_review/jobs/547323704#L220

2021-11-09 15:03 UTC, perlpunk commented on openqa_review/openqa_review.py
> +    """ Initialize data for redmine issues. """
Not sure what blank lines are needed.

2021-11-09 15:25 UTC, perlpunk commented on openqa_review/openqa_review.py
> +    """ Initialize data for redmine issues. """
It's green: https://github.com/os-autoinst/openqa_review/pull/190/checks?check_run_id=4153411494

2021-11-09 15:28 UTC, okurz approved these changes

2021-11-09 15:28 UTC, merged