Add GitHub Workflow for testing
os-autoinst/openqa_review pull request #196
Opened 2021-11-12 19:01 UTC by perlpunk

Issue: https://progress.opensuse.org/issues/102350

2021-11-12 21:29 UTC, okurz requested changes
good first step. I am confident with your YAML knowledge you can reduce the duplication :)

2021-11-12 21:33 UTC, perlpunk commented
>  you can reduce the duplication

GHA YAML doesn't support aliases :-/

2021-11-14 20:29 UTC, okurz requested changes

2021-11-14 20:29 UTC, okurz commented on .github/workflows/python-package.yaml
> +    branches: [ master ]
I would just simplify to

```suggestion
on: [push, pull_request]
```

2021-11-14 20:29 UTC, okurz commented on .github/workflows/python-package.yaml
> +        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
why do you need to care about these dependencies when it should be ok to just install tox and call it?

2021-11-14 20:29 UTC, okurz commented on .github/workflows/python-package.yaml
> +        tox -e py"${PYTHONVERSION/./}"
both https://github.com/tox-dev/tox-gh as well as https://opensourcelibs.com/lib/tox-gh-actions look a bit nicer

2021-11-16 12:51 UTC, perlpunk commented on .github/workflows/python-package.yaml
> +        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
We can improve this, but right now it would e the easiest to merge this.
Once the repo has at least one workflow, changes are made easier.

2021-11-16 14:03 UTC, Martchus approved these changes
I have nothing against merging this as long as it works. We can leave further tweaks for later.

2021-11-16 17:07 UTC, okurz reviewed
Yes, we can do the improvements later but with doc tests not yet working I would prefer to not yet merge

2021-11-16 17:20 UTC, perlpunk commented
> Yes, we can do the improvements later but with doc tests not yet working I would prefer to not yet merge

doctests are also not working in Travis CI currently. So I don't see why you don't want this.

2021-11-16 17:22 UTC, okurz commented
Wait, they are not? Huh. So, what should we do to fix them?

2021-11-16 17:24 UTC, perlpunk commented
https://github.com/os-autoinst/openqa_review/blob/master/tox.ini#L13

```
# TODO doctests fail to find modules on travis
```
So you want to wait with this until doctests are running? Why?

2021-11-16 18:54 UTC, okurz approved these changes
> So you want to wait with this until doctests are running? Why?

No, I only wanted to clarify that we know why they are not running. So all looks good then

2021-11-17 10:11 UTC, merged

2021-11-17 10:14 UTC, perlpunk commented
Now after merge the coverage and style tests are failing, which is very weird, because all passed when I ran this in my fork.
https://github.com/os-autoinst/openqa_review/actions/runs/1471050827
Was something merged in between that did not pass those tests?

2021-11-17 10:54 UTC, okurz commented
as we discussed: Yes, @Martchus broke it :)