Fix querying the latest comment of progress issues
os-autoinst/openqa_review pull request #197
Opened 2021-11-15 14:09 UTC by Martchus

* Fix assertion error we see in pipline runs which happens when trying to
  find the latest comment for a progress ticket (and there was no comment
  when initializing the `Issue` object)
* Support redmine tickets when querying the last comment
* See https://progress.opensuse.org/issues/102440

2021-11-15 14:18 UTC, okurz commented
In the second git commit message s/pipline/pipeline/

2021-11-15 14:32 UTC, okurz requested changes

2021-11-15 14:32 UTC, okurz commented on openqa_review/openqa_review.py
> +        self.json = browser.json_rpc_get("/jsonrpc.cgi", "Bug.get", {"ids": [self.bugid]})["result"]["bugs"][0]
I prefer the previous approach that uses dependency injection. Why did you change that?

2021-11-15 14:32 UTC, okurz commented on openqa_review/openqa_review.py
> +            # self.issue_type == 'redmine':
dead code? Better make it explicit by either

```python
assert self.issue_type == "bugzilla" or self.issue_type == "redmine", "Only bugzilla or redmine supported as issue type"
if self.issue_type == "bugzilla":
…
else:
…
```

or

```python
if self.issue_type == "bugzilla":
…
if self.issue_type == "redmine":
…
else:
    assert False, "Only bugzilla or redmine supported as issue type"
```

but I would like a proper object-oriented approach better and avoid the if-else

2021-11-15 14:32 UTC, okurz commented on tests/test_openqa_review.py
> +    )
with spreading over so many lines I think it already helps to create a helper function to create the correct testing issue, e.g.


```python
def issue_factory(bugref, bugref_href, args):
    browser = browser_factory(args)
    return openqa_review.Issue(bugref, bugref_href, True, browser, browser)
…

def test_querying_last_bugzilla_comment():
    args = cache_test_args_factory()
    args.load_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "bugzilla")
    issue = issue_factory("boo#0815", "https://bugzilla.opensuse.org/show_bug.cgi?id=0815", args)
    (comment_date, comment_text) = issue.last_comment
    …
```

2021-11-15 14:37 UTC, Martchus commented on openqa_review/openqa_review.py
> +        self.json = browser.json_rpc_get("/jsonrpc.cgi", "Bug.get", {"ids": [self.bugid]})["result"]["bugs"][0]
It seemed needless to pass the browser as argument when it is also a member variable of the object. We already use `self.bugzilla_browser` in other places so this makes it also more consistent.

2021-11-15 14:40 UTC, Martchus commented on openqa_review/openqa_review.py
> +            # self.issue_type == 'redmine':
This is not dead code. It is a comment which says what "else" means here. I'd just followed what we had elsewhere. I'll change all occurrences to the 2nd form in your comment. However, I see a refactoring to use inheritance here out of scope.

2021-11-15 15:39 UTC, perlpunk commented
I'm wondering in which case this actually happens.
Both `last_comment_date` and `last_comment_text` should be set to something in case of redmine, so when is the line
`if not self.last_comment_date or self.last_comment_text is None:` actually triggered?
```
        self.last_comment_date = datetime.datetime.strptime(self.json["updated_on"], "%Y-%m-%dT%H:%M:%SZ")
        self.last_comment_text = ""
```

2021-11-15 15:42 UTC, Martchus commented
Good question. Maybe that's actually only the case when the bugref is an invalid one?

2021-11-15 15:49 UTC, Martchus commented
No - that isn't it. If the issue type isn't set, `last_comment` would not be called in the first place.

2021-11-15 15:52 UTC, Martchus commented
The actual problem is the condition itself. That's basically the problem:

```
>>> foo = None
>>> bar = None
>>> not foo or bar is None
True
>>> not foo or bar
True
```

2021-11-16 08:11 UTC, okurz approved these changes

2021-11-16 14:44 UTC, kalikiana approved these changes

2021-11-16 16:07 UTC, merged