Improve GitHub workflow and remove Travis CI
os-autoinst/openqa_review pull request #204
Opened 2021-11-19 15:41 UTC by perlpunk

Issue: https://progress.opensuse.org/issues/102350

I added a tox plugin like requested from @okurz but also kept the style/coverage tests separate. This way we see immediately which extra test failed without having to dig into the test log.

2021-11-19 15:43 UTC, okurz requested changes
Any git commit with "and" in the subject line is a good indication that it should be more than one commit :) Also I suggest to keep travis CI config around. It should not harm. All other changes look ok in general though

2021-11-19 17:08 UTC, perlpunk commented
Not sure why we should keep the travis config, but I did, and for completeness I added doctests there ass well.

2021-11-21 14:10 UTC, okurz approved these changes

2021-11-21 14:11 UTC, okurz commented
I don't think we need to keep travis CI information around for longer but just remove it from the one commit. Sorry, that was unclear. It's ok either way, without removing travis CI information or with it included in a separate commit

2021-11-22 15:07 UTC, merged

2021-11-22 15:16 UTC, okurz commented
@perlpunk please keep in mind that we also have mergify in this repo and it's currently configured to wait for two approvals. So the best practice is to not self-merge but just let mergify do it when all requirements are fulfilled.