Draft: Configurable no-reminder message pattern
os-autoinst/openqa_review pull request #208
Opened 2022-02-11 15:42 UTC by baierjan

Have a configurable blocklist message or pattern and when encountered no reminders are sent.

Reference: https://progress.opensuse.org/issues/106368

2022-02-11 16:06 UTC, mimi1vx commented on openqa_review/openqa_review.py
> +NO_REMINDER_REGEX = "NO_REMINDER"
why not `NO_REMINDER_REGEX = re.compile(r"pattern")`

2022-02-11 16:07 UTC, mimi1vx commented on openqa_review/openqa_review.py
> +    pattern = re.compile(str(ignore_pattern))
why converting string to string?

2022-02-11 16:15 UTC, mimi1vx commented on openqa_review/openqa_review.py
> +    reminder_comments.add_argument(
you can add parameter `type=re.compile` and returned value will be precompiled regexp

2022-02-11 17:01 UTC, okurz commented on openqa_review/openqa_review.py
> +NO_REMINDER_REGEX = "NO_REMINDER"
well, if you include it then please make it WONTFIX :)

2022-02-11 17:05 UTC, okurz requested changes

2022-02-11 17:05 UTC, okurz commented on openqa_review/openqa_review.py
> +                    softfail_reason = field["title"]
```suggestion
                softfail_reason = field["text_data"] if "text_data" in field else field["title"]
```

2022-02-11 18:32 UTC, baierjan commented on openqa_review/openqa_review.py
> +    pattern = re.compile(str(ignore_pattern))
To support `None` as a pattern.

2022-02-11 18:33 UTC, baierjan commented on openqa_review/openqa_review.py
> +    reminder_comments.add_argument(
Ah, `type=`, thanks for the tip. According to documentation, it looked that I need a custom `Action` to be able to have the pattern compiled during parsing. I would like to have that pre-compiled here.

2022-02-11 18:37 UTC, baierjan commented on openqa_review/openqa_review.py
> +NO_REMINDER_REGEX = "NO_REMINDER"
I just used the suggestion from the ticket (and @okurz ), that the default should be just `NO_REMINDER` and we shall do an extra configuration for o3 and osd. `WONTFIX|NO_REMINDER` is a very good candidate for a default value though.

2022-02-11 18:39 UTC, baierjan commented on openqa_review/openqa_review.py
> +                    softfail_reason = field["title"]
Yes, that is probably a good idea. There were more lines during the debugging.

2022-02-11 18:41 UTC, baierjan commented on openqa_review/openqa_review.py
> +    pattern = re.compile(str(ignore_pattern))
As I have a now a default value everywhere, it is probably not necessary anymore and it will be refactored anyways (as hinted below)

2022-02-11 18:42 UTC, mimi1vx commented on openqa_review/openqa_review.py
> +    pattern = re.compile(str(ignore_pattern))
why support `None`?

Plus this construction creates compiled regexp to find string `"None"` which isn't desired behaviour//

2022-02-11 18:44 UTC, mimi1vx commented on openqa_review/openqa_review.py
> +                    softfail_reason = field["title"]
suggested construction is common in Perl:D but much less in python

2022-02-11 18:49 UTC, okurz commented
Now if you could just fix the style issues I have introduced :)

2022-02-11 18:51 UTC, baierjan commented on openqa_review/openqa_review.py
> +    pattern = re.compile(str(ignore_pattern))
Oh, I somewhat assumed Python would be smarter and I will end up with an empty string. Good to know that I would not.

2022-02-11 18:53 UTC, baierjan commented
> Now if you could just fix the style issues I have introduced :)

There were issues even before, I expected changes so I did not run `black` yet.

2022-02-14 09:43 UTC, mimi1vx commented on openqa_review/openqa_review.py
> +    pattern = re.compile(str(ignore_pattern))
never, `str` defaults to `repr` if isnt implemented + you want something than empty string

2022-02-14 12:07 UTC, mimi1vx approved these changes

2022-02-14 12:46 UTC, okurz approved these changes

2022-02-14 12:46 UTC, merged

2022-02-14 14:00 UTC, perlpunk commented on openqa_review/openqa_review.py
> +                    softfail_reason = field["title"]
In perl it would have probably been enough to do
`$softfail_reason = $field{text_data} // $field{title}`
:)