Rename variable just to confirm if CI fails
os-autoinst/openqa_review pull request #217
Opened 2022-12-02 14:57 UTC by kalikiana

Expecting to see the following:

    fixture 'mocker' not found

2022-12-02 15:26 UTC, perlpunk approved these changes

2022-12-02 16:10 UTC, r-richardson approved these changes

2022-12-02 17:15 UTC, okurz requested changes
CI checks fail in https://github.com/os-autoinst/openqa_review/actions/runs/3602936327/jobs/6070510255#step:5:38 with

```
flake8 run-test: commands[0] | flake8
Traceback (most recent call last):
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8/options/parse_args.py", line 51, in parse_args
    option_manager.register_plugins(plugins)
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8/options/manager.py", line 259, in register_plugins
    add_options(self)
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8_quotes/__init__.py", line 109, in add_options
    cls._register_opt(parser, '--quotes', action='store',
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8_quotes/__init__.py", line 99, in _register_opt
    parser.add_option(*args, **kwargs)
  File "/home/runner/work/openqa_review/openqa_review/.tox/flake8/lib/python3.10/site-packages/flake8/options/manager.py", line 281, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/argparse.py", line 1428, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'choice' is not callable
ERROR: InvocationError for command /home/runner/work/openqa_review/openqa_review/.tox/flake8/bin/flake8 (exited with code 1)
```

Is this related?

EDIT: Oh and please make sure the git commit message subject line states the "Why", not the "What"

2022-12-02 19:27 UTC, mimi1vx approved these changes

2022-12-03 09:30 UTC, okurz approved these changes

2022-12-03 09:31 UTC, merged

2022-12-16 14:28 UTC, perlpunk commented on tox.ini
> +    flake8<6.0.0  # TODO remove pinned version once https://github.com/zheller/flake8-quotes/pull/111 is merged.
Note: https://github.com/zheller/flake8-quotes/pull/111 was merged, but no release yet