Mention NO_REMINDER_REGEX as additional option to prevent reminders
os-autoinst/openqa_review pull request #222
Opened 2024-08-01 18:14 UTC by okurz

Related progress issue: https://progress.opensuse.org/issues/106368

2024-08-01 20:09 UTC, okurz commented on openqa_review/openqa_review.py
> +            "no_reminder_pattern": NO_REMINDER_PATTERN.pattern,
done

2024-08-01 20:32 UTC, baierjan approved these changes

2024-08-02 08:22 UTC, perlpunk requested changes

2024-08-02 08:22 UTC, perlpunk commented on openqa_review/openqa_review.py
> +            "no_reminder_pattern": NO_REMINDER_REGEX.pattern,
```suggestion
            "no_reminder_pattern": args.ignore_pattern.pattern,
```

2024-08-02 08:36 UTC, baierjan commented on openqa_review/openqa_review.py
> +            "no_reminder_pattern": NO_REMINDER_REGEX.pattern,
Ah, right, `NO_REMINDER_REGEX` is just the default value and it can be configured. Nice catch!

2024-08-02 10:05 UTC, perlpunk commented on openqa_review/openqa_review.py
> +4. For "record_soft_failure" references the reference is removed or matches the pattern $no_reminder_pattern
```suggestion
4. For "record_soft_failure" references the reference is removed or matches the pattern /$no_reminder_pattern/
```
or
```suggestion
4. For "record_soft_failure" references the reference is removed or matches the pattern '$no_reminder_pattern'
```

2024-08-02 10:13 UTC, perlpunk commented
huh.
https://github.com/os-autoinst/openqa_review/actions/runs/10213705644/job/28259653606?pr=222#step:7:87
```
E           AttributeError: 'NoneType' object has no attribute 'pattern'
```

2024-08-02 10:20 UTC, okurz commented on openqa_review/openqa_review.py
> +4. For "record_soft_failure" references the reference is removed or matches the pattern $no_reminder_pattern
Done.

2024-08-02 10:20 UTC, okurz commented
> huh. https://github.com/os-autoinst/openqa_review/actions/runs/10213705644/job/28259653606?pr=222#step:7:87
> 
> ```
> E           AttributeError: 'NoneType' object has no attribute 'pattern'
> ```
> 
> ah. there is a test doing `args.ignore_pattern = None`. maybe not a useful thing to do, as the script makes sure it always has a default. Not sure if it's even possible to set it to None via a command line option.

True. I changed it in the test to `args.ignore_pattern = re.compile("THIS_WILL_NOT_MATCH")`

2024-08-02 10:30 UTC, perlpunk approved these changes

2024-08-02 10:31 UTC, merged